### ISSUE TITLE
Refresh will occasionally get stuck

### ISSUE THREAD

**Issue by riley-williams** [dyountmusic/f5oclock-iOS#3]
Certain events such as locking the phone sometimes result in refreshControl.endRefreshing() not being called. This results in the app being in a state where it is never able to refresh.

**Comment by dyountmusic** [comment]
Refresh control beginRefresh() and endRefresh() are now no longer being called when the app auto-refreshes data in the background. A new method updateUIWithoutRefreshControl has been added to address this scenario.
